apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-vanilla-pvc-data
  namespace: minecraft-vanilla
spec:
  storageClassName: ""
  volumeName: minecraft-vanilla-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft-vanilla
  name: minecraft-vanilla
  namespace: minecraft-vanilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-vanilla
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minecraft-vanilla
    spec:
      volumes:
        - name: minecraft-vanilla-data
          persistentVolumeClaim:
            claimName: minecraft-vanilla-pvc-data
      containers:
        - name: minecraft-vanilla
          image: itzg/minecraft-server
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-vanilla-config
          env:
            - name: OPS
              valueFrom:
                secretKeyRef:
                  name: minecraft-vanilla-secret
                  key: OPS
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minecraft-vanilla-data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "1"
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: minecraft-vanilla-svc
  namespace: minecraft-vanilla
spec:
  selector:
    app: minecraft-vanilla
  ports:
    - port: 25565
      name: minecraft-vanilla
      targetPort: 25565
      protocol: TCP
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minecraft-vanilla-http-route
  namespace: minecraft-vanilla
  labels:
    shared-gateway-access: "true"
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "minecraftvanilla.snoozyhomelab.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: minecraft-vanilla-svc
          kind: Service
          namespace: minecraft-vanilla
          port: 25565

---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft-vanilla-tcp-route
  namespace: minecraft-vanilla
  labels:
    shared-gateway-access: "true"
spec:
  parentRefs:
    - name: main-gateway
      namespace: envoy-gateway-system
      sectionName: minecraft-tcp
  rules:
    - backendRefs:
        - name: minecraft-vanilla-svc
          kind: Service
          namespace: minecraft-vanilla
          port: 25565