version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:2024.5.0
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data