version: "3.8"

services:
  minecraft_mods:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      MEMORY: "4G"
      EULA: "TRUE"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: '$CF_API_KEY'
      CF_SLUG: "immersive-trailer-experience"
    volumes:
      - ./minecraft_mods_data:/data

  minecraft_vanilla:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      MEMORY: "2G"
      EULA: "TRUE"
    volumes:
      - ./minecraft_vanilla_data:/data